# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: part_identifier.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15part_identifier.proto\x12\x0fPart_Identifier\"&\n\x13IdentifyPartRequest\x12\x0f\n\x07part_id\x18\x01 \x01(\t\"k\n\x14IdentifyPartResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x11\n\timage_url\x18\x03 \x01(\t\x12\x13\n\x0bpart_number\x18\x04 \x01(\t\x12\x10\n\x08location\x18\x05 \x01(\t2v\n\x15PartIdentifierService\x12]\n\x0cIdentifyPart\x12$.Part_Identifier.IdentifyPartRequest\x1a%.Part_Identifier.IdentifyPartResponse\"\x00\x42\x14Z\x12./PartIdentifierpbb\x06proto3')



_IDENTIFYPARTREQUEST = DESCRIPTOR.message_types_by_name['IdentifyPartRequest']
_IDENTIFYPARTRESPONSE = DESCRIPTOR.message_types_by_name['IdentifyPartResponse']
IdentifyPartRequest = _reflection.GeneratedProtocolMessageType('IdentifyPartRequest', (_message.Message,), {
  'DESCRIPTOR' : _IDENTIFYPARTREQUEST,
  '__module__' : 'part_identifier_pb2'
  # @@protoc_insertion_point(class_scope:Part_Identifier.IdentifyPartRequest)
  })
_sym_db.RegisterMessage(IdentifyPartRequest)

IdentifyPartResponse = _reflection.GeneratedProtocolMessageType('IdentifyPartResponse', (_message.Message,), {
  'DESCRIPTOR' : _IDENTIFYPARTRESPONSE,
  '__module__' : 'part_identifier_pb2'
  # @@protoc_insertion_point(class_scope:Part_Identifier.IdentifyPartResponse)
  })
_sym_db.RegisterMessage(IdentifyPartResponse)

_PARTIDENTIFIERSERVICE = DESCRIPTOR.services_by_name['PartIdentifierService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\022./PartIdentifierpb'
  _IDENTIFYPARTREQUEST._serialized_start=42
  _IDENTIFYPARTREQUEST._serialized_end=80
  _IDENTIFYPARTRESPONSE._serialized_start=82
  _IDENTIFYPARTRESPONSE._serialized_end=189
  _PARTIDENTIFIERSERVICE._serialized_start=191
  _PARTIDENTIFIERSERVICE._serialized_end=309
# @@protoc_insertion_point(module_scope)
