# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import part_identifier_pb2 as part__identifier__pb2


class PartIdentifierServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.IdentifyPart = channel.unary_unary(
                '/Part_Identifier.PartIdentifierService/IdentifyPart',
                request_serializer=part__identifier__pb2.IdentifyPartRequest.SerializeToString,
                response_deserializer=part__identifier__pb2.IdentifyPartResponse.FromString,
                )


class PartIdentifierServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def IdentifyPart(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PartIdentifierServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'IdentifyPart': grpc.unary_unary_rpc_method_handler(
                    servicer.IdentifyPart,
                    request_deserializer=part__identifier__pb2.IdentifyPartRequest.FromString,
                    response_serializer=part__identifier__pb2.IdentifyPartResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Part_Identifier.PartIdentifierService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class PartIdentifierService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def IdentifyPart(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Part_Identifier.PartIdentifierService/IdentifyPart',
            part__identifier__pb2.IdentifyPartRequest.SerializeToString,
            part__identifier__pb2.IdentifyPartResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
